version: '3'
services:

  environment:
    VPN_SERVER_IP:
    OVPN_DATA:"ovpnData"

  
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - openvpn:/etc/openvpn



volumes:
    ovpnData:

# network:
#     frontend:
#     backend: