version: '3'
services:
  ansible:
    # 如果你同时指定了 image 和 build 两个标签，那么 Compose 会构建镜像并且把镜像命名为 image 后面的那个名字。
    # 如果不指定，则会以docker-compose.yml文件所在目录+此服务的名字，如：docker_ansible_ansible
    # image: registry.cn-beijing.aliyuncs.com/univerdream/ansible:test
    image: registry.cn-beijing.aliyuncs.com/univerdream/ansible:latest
    # image: registry.cn-beijing.aliyuncs.com/univerdream/ansible:1.0
    # build: .
    # build: ./dir
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
      # args:
      #   buildno: 1
    # ports:
    #  - "5000:5000"
    volumes:
     # - ../src: /src
     - $PWD/.ansible: /root/.ansible
     - $PWD/.ssh/id_rsa: /root/.ssh/id_rsa
  # redis:
  #   image: "redis:3.0.7"
